export const NEWS_TOPICS = [
  "Crime",
  "Technology",
  "Economics",
  "Business",
  "Sports",
  "Defence",
  "Politics & Government",
  "Lifestyle & Culture",
  "Entertainment",
  "Environment & Climate",
  "Health & Wellness",
  "Education",
  "Generative AI",
];
